### ISSUE TITLE
Problema con el rango de los datos

### ISSUE THREAD

**Issue by malejandrogarcia** [mchalela/GriSPy#1]
Si en el archivo **example.py** se cambia la línea donde se generan los datos por 
**data = np.random.uniform(-10, 10, size=(Npoints, dim))**, 
Python devuelve el warning  **/home/ag/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:378: RuntimeWarning: divide by zero encountered in true_divide** y el programa entra en un bucle infinito. En el ejemplo original el rango es -50, 50 y funciona bien. Bajando hasta -20, 20 no hay problema.

**Comment by mchalela** [comment]
No encuentro problemas en **example.py**. Cualquier valor de Lbox anda bien, incluido **Lbox=20** que resulta en la linea **data = np.random.uniform(-10, 10, size=(Npoints, dim))**.
Incluso escribiendo explicitamente la linea: **...-Lbox / 2, Lbox / 2...   -->   ...-10,10...** anda sin problemas.
Te parece bien copiar el codigo del example.py que editaste en este issue asi lo probamos?

**Comment by malejandrogarcia** [comment]
Hola Martín.
Qué raro... Ahora no estoy en mi casa, pero apenas llegue les paso el
archivo.
Nos vemos!

**Comment by mchalela** [comment]
Con los cambios que hechos creo que quedo resuelto este issue. Lo cierro.
