### ISSUE TITLE
nearest_neighbors search hanging on particular coordinate

### ISSUE THREAD

**Issue by asasama12** [mchalela/GriSPy#18]
Having a strange issue where the nearest neighbor search gets stuck on a specific point (index 147 in this dataset), but only if that point is included in a set.  If I run the nearest neighbor search on only that point, it successfully runs.  I've converted the coordinates to float64 as that posed an issue in the past.   

The point that is giving an issue is circled in the bottom image, I noticed it is far from all other points compared to all other data points.  Not sure if that's related or coincidence. 

**Index 147 runs by itself but does not run when included with index 146**
![image](https://user-images.githubusercontent.com/41748563/139901612-112ddc0a-9ad1-4e87-8cbf-5f61a9948c88.png)
**index 147 is far from other points**
![image](https://user-images.githubusercontent.com/41748563/139901963-5995dd9e-c05a-4e3f-9132-99d47ddc32b5.png)

**Comment by mchalela** [comment]
Hello @asasama12 , I'm not sure a priori what could be causing the problem. Could you please: 
a) comment what version of Grispy are you using?
b) provide a file with your data coords to reproduce the problem?

We are working on a new release, so if we identify the problem we can include a fix to this issue in the new release.

**Comment by asasama12** [comment]
updated from 0.0.4 to 0.1.0 and it works now.  Here's the file if you want to look at it, but issue has been resolved.  Thanks! 
[data.csv](https://github.com/mchalela/GriSPy/files/7469180/data.csv)

**Comment by mchalela** [comment]
I'm glad to hear that!

Closing this
