### ISSUE TITLE
'invalid entry in coordinates array' when including more than 400 coordinate entries

### ISSUE THREAD

**Issue by asasama12** [mchalela/GriSPy#7]
Having a strange issue with a particular dataset, where if I try to run 'gsp = GriSPy(coords)' I get the following error:

ValueError                                Traceback (most recent call last)
<ipython-input-34-6b102f65f9d1> in <module>
----> 1 gsp = GriSPy(coords)
      2 
      3 shell_neighbors = {}
      4 for index, coord in enumerate(coords):
      5 

<attrs generated init grispy.core.GriSPy> in __init__(self, data, N_cells, periodic, metric, copy_data)
     14         __attr_validator_metric(self, __attr_metric, self.metric)
     15         __attr_validator_copy_data(self, __attr_copy_data, self.copy_data)
---> 16     self.__attrs_post_init__()

~/tensor_env/lib/python3.8/site-packages/grispy/core.py in __attrs_post_init__(self)
    185             periodic=self.periodic, dim=self.dim_)
    186 
--> 187         self.grid_, self.k_bins_ = self._build_grid(
    188             data=self.data,
    189             N_cells=self.N_cells,

~/tensor_env/lib/python3.8/site-packages/grispy/core.py in _build_grid(self, data, N_cells, dim, epsilon)
    379         grid = {}
    380         if N_cells ** dim < len(data):
--> 381             compact_ind = np.ravel_multi_index(
    382                 k_digit.T, (N_cells,) * dim, order="F")
    383 

<__array_function__ internals> in ravel_multi_index(*args, **kwargs)

ValueError: invalid entry in coordinates array

I thought maybe there was a particular entry in my array that was causing an issue so attempted to narrow it down by running gsp = GriSPy(coords[:100]) , gsp = GriSPY(coords{100:200]) etc and found that any selection of 400 entries works, but as soon as I add a 401st entry I get the above error.  

I've used this package on a different dataset with no issues.  

Any thoughts?

**Comment by mchalela** [comment]
I've never seen that error before :(
What type of coordinates are you using? float32, float64, integers...? If they are floats try casting them to float64. Also, are they very small numbers? like 1e-10 or something like that?

**Comment by asasama12** [comment]
Yes! They were float32, now working after converting to float64

**Comment by mchalela** [comment]
Great!!
I'll keep the issue open until we fix this. It should work fine with float32.
Thanks for your comment!
